### ISSUE TITLE
Self keyword missing

### ISSUE THREAD

**Issue by SMadani** [arcanefoam/mde_listings#3]
There is no "self" defined for Epsilon's rule-based languages.

**Comment by arcanefoam** [comment]
I was actually thinking about improving the language hierarchies to have an ERL language definition that would include rule base specifics: pre, post, self, etc....
For the time being I will add it to the EOL definition.

**Comment by arcanefoam** [comment]
Fixed in #20e3611

**Comment by SMadani** [comment]
Awesome, thanks!
